export { default as NextmartLogo } from "./NextmartLogo.svg"
export { default as ArmsLogo } from "./ArmsLogo.svg"
export { default as ArmsPhpLogo } from "./ArmsPhpLogo.svg"
export { default as ClimateLogo } from "./ClimateLogo.svg"
export { default as CookeezLogo } from "./CookeezLogo.svg"
export { default as CovidtraxLogo } from "./CovidtraxLogo.svg"
export { default as DaysbeyondLogo } from "./DaysbeyondLogo.svg"
export { default as FilmstackLogo } from "./FilmstackLogo.svg"
export { default as KalciLogo } from "./KalciLogo.svg"
export { default as NuklearbrainLogo } from "./NuklearbrainLogo.svg"
export { default as PikturesLogo } from "./PikturesLogo.svg"
export { default as SrinivasLogo } from "./SrinivasLogo.svg"
export { default as XReconLogo } from "./XReconLogo.svg"
export { default as YoatubeLogo } from "./YoatubeLogo.svg"
export { default as VortexaLogo } from "./VortexaLogo.svg"
export { default as PotholeLogo } from "./PotholeLogo.webp"
export { default as ProductRecLogo } from "./ProductRecLogo.webp"
export { default as FinSageLogo } from "./FinSageLogo.webp"
export { default as TrafficSignLogo } from "./TrafficSignLogo.webp"
export { default as SmartupcycleLogo } from "./SmartupcycleLogo.webp"
export { default as CodingPuzzlesLogo } from "./CodingPuzzlesLogo.webp"
export { default as DevmonkLogo } from "./DevmonkLogo.svg"
export { default as DreamSoft4uLogo } from "./DreamSoft4uLogo.svg"
export { default as TextToHandwrittenLogo } from "./TextToHandwrittenLogo.svg"
export { default as KVLogo } from "./KVLogo.svg"
export { default as VITLogo } from "./VITLogo.svg"




