export { default as KalciShots } from "./Kalci.webp"
export { default as NuklearbrainShots } from "./Nuklearbrain.webp"
export { default as ClimateShots } from "./Climate.webp"
export { default as CookeezShots } from "./Cookeez.webp"
export { default as CovidTraxShots } from "./CovidTrax.webp"
export { default as FilmstackShots } from "./Filmstack.webp"
export { default as Armsv1Shots } from "./ARMSv1.webp"
export { default as DaysbeyondShots } from "./Daysbeyond.webp"
export { default as PikturesShots } from "./Piktures.webp"
export { default as SrinivasShots } from "./Srinivas.webp"
export { default as YoatubeShots } from "./Yoatube.webp"
export { default as XreconShots } from "./Xrecon.webp"
export { default as Armsv2Shots } from "./ARMSv2.webp"
export { default as NextmartShots } from "./NextMart.webp"
export { default as VortexaShots } from "./Vortexa.webp"
export { default as Armsv3Shots } from "./ARMSv3.webp"
export { default as EcommerceRecShots } from "./EcommerceRec.png"
export { default as PotholeShots } from "./PotholeShots.webp"
export { default as ProductRecShots } from "./ProductRecShots.webp"
export { default as FinSageShots } from "./FinSageShots.webp"
export { default as TrafficSignShots } from "./TrafficSignShots.webp"
export { default as SmartupcycleShots } from "./SmartupcycleShots.webp"
export { default as CodingPuzzlesShots } from "./CodingPuzzlesShots.webp"
export { default as DevmonkShot } from "./DevmonkShot.svg"
export { default as DreamSoft4uShot } from "./DreamSoft4uShot.svg"
export { default as TextToHandwrittenShots } from "./TextToHandwrittenShots.svg"
export { default as SchoolingShot } from "./SchoolingShot.svg"
export { default as BachelorsShot } from "./BachelorsShot.svg"



